import './code-analyzer.test';
import './assignment.test';
import './condition.test';
import './functions.test';
import './while.test';
import './return.test';
import './variables.test';
import './valueExtractor.test';
import './elementsTableController.test';